/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PromosRouteImport } from './routes/promos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventosIndexRouteImport } from './routes/eventos.index'
import { Route as Zona10CategoryRouteImport } from './routes/zona-10.$category'
import { Route as LugarSlugRouteImport } from './routes/lugar.$slug'
import { Route as EventosSlugRouteImport } from './routes/eventos.$slug'
import { Route as DashboardUpgradeRouteImport } from './routes/dashboard.upgrade'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PromosRoute = PromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => rootRouteImport,
} as any)
const Zona10CategoryRoute = Zona10CategoryRouteImport.update({
  id: '/zona-10/$category',
  path: '/zona-10/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const LugarSlugRoute = LugarSlugRouteImport.update({
  id: '/lugar/$slug',
  path: '/lugar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosSlugRoute = EventosSlugRouteImport.update({
  id: '/eventos/$slug',
  path: '/eventos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUpgradeRoute = DashboardUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/promos': typeof PromosRoute
  '/signup': typeof SignupRoute
  '/dashboard/upgrade': typeof DashboardUpgradeRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/lugar/$slug': typeof LugarSlugRoute
  '/zona-10/$category': typeof Zona10CategoryRoute
  '/eventos/': typeof EventosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/promos': typeof PromosRoute
  '/signup': typeof SignupRoute
  '/dashboard/upgrade': typeof DashboardUpgradeRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/lugar/$slug': typeof LugarSlugRoute
  '/zona-10/$category': typeof Zona10CategoryRoute
  '/eventos': typeof EventosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/promos': typeof PromosRoute
  '/signup': typeof SignupRoute
  '/dashboard/upgrade': typeof DashboardUpgradeRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/lugar/$slug': typeof LugarSlugRoute
  '/zona-10/$category': typeof Zona10CategoryRoute
  '/eventos/': typeof EventosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscar'
    | '/dashboard'
    | '/login'
    | '/promos'
    | '/signup'
    | '/dashboard/upgrade'
    | '/eventos/$slug'
    | '/lugar/$slug'
    | '/zona-10/$category'
    | '/eventos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/dashboard'
    | '/login'
    | '/promos'
    | '/signup'
    | '/dashboard/upgrade'
    | '/eventos/$slug'
    | '/lugar/$slug'
    | '/zona-10/$category'
    | '/eventos'
  id:
    | '__root__'
    | '/'
    | '/buscar'
    | '/dashboard'
    | '/login'
    | '/promos'
    | '/signup'
    | '/dashboard/upgrade'
    | '/eventos/$slug'
    | '/lugar/$slug'
    | '/zona-10/$category'
    | '/eventos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscarRoute: typeof BuscarRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PromosRoute: typeof PromosRoute
  SignupRoute: typeof SignupRoute
  EventosSlugRoute: typeof EventosSlugRoute
  LugarSlugRoute: typeof LugarSlugRoute
  Zona10CategoryRoute: typeof Zona10CategoryRoute
  EventosIndexRoute: typeof EventosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promos': {
      id: '/promos'
      path: '/promos'
      fullPath: '/promos'
      preLoaderRoute: typeof PromosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zona-10/$category': {
      id: '/zona-10/$category'
      path: '/zona-10/$category'
      fullPath: '/zona-10/$category'
      preLoaderRoute: typeof Zona10CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lugar/$slug': {
      id: '/lugar/$slug'
      path: '/lugar/$slug'
      fullPath: '/lugar/$slug'
      preLoaderRoute: typeof LugarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$slug': {
      id: '/eventos/$slug'
      path: '/eventos/$slug'
      fullPath: '/eventos/$slug'
      preLoaderRoute: typeof EventosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/upgrade': {
      id: '/dashboard/upgrade'
      path: '/upgrade'
      fullPath: '/dashboard/upgrade'
      preLoaderRoute: typeof DashboardUpgradeRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardUpgradeRoute: typeof DashboardUpgradeRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardUpgradeRoute: DashboardUpgradeRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscarRoute: BuscarRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PromosRoute: PromosRoute,
  SignupRoute: SignupRoute,
  EventosSlugRoute: EventosSlugRoute,
  LugarSlugRoute: LugarSlugRoute,
  Zona10CategoryRoute: Zona10CategoryRoute,
  EventosIndexRoute: EventosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
