export type DbEvent = {
  id: string;
  title: string;
  slug: string;
  description: string | null;
  category: string;
  zone: string;
  venue_name: string | null;
  place_id: string | null;
  source: string;
  date_start: string;
  date_end: string | null;
  price: number | null;
  is_free: boolean;
  image_url: string | null;
  contact_link: string | null;
  sponsored: boolean;
  featured: boolean;
  tags: string[];
  status: 'pending' | 'published';
};

export type DbBankPromotion = {
  id: string;
  bank: string;
  external_id: string;
  merchant_name: string;
  place_id: string | null;
  title: string;
  discount_label: string;
  discount_pct: number | null;
  category: string | null;
  terms: string | null;
  image_url: string | null;
  source_url: string;
  valid_from: string | null;
  valid_until: string | null;
  is_active: boolean;
  last_seen_at: string;
  created_at: string;
  updated_at: string;
};
