export type DbEvent = {
  id: string;
  title: string;
  slug: string;
  description: string | null;
  category: string;
  zone: string;
  venue_name: string | null;
  place_id: string | null;
  source: string;
  date_start: string;
  date_end: string | null;
  price: number | null;
  image_url: string | null;
  contact_link: string | null;
  sponsored: boolean;
  featured: boolean;
  tags: string[];
  status: 'pending' | 'published';
};
